
Vagrant.configure(2) do |config|

    NodeCount = 2
  
    (1..NodeCount).each do |i|
      config.vm.define "centosvm0#{i}" do |node|
        node.vm.box = "centos/7"
        node.vm.hostname = "centosvm0#{i}.example.com"
        node.vm.network "private_network", ip: "172.42.42.10#{i}"
        node.vm.provider "virtualbox" do |v|
          v.name = "centosvm0#{i}"
          v.memory = 1024
          v.cpus = 1
        end
      end
    end
  
  end