version: '3'
services:
  db:
      image: mysql:8
      container_name: db
      restart: unless-stopped
      tty: true
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: mydb
        MYSQL_ROOT_PASSWORD: password
      volumes:
        - ./dbdata:/var/lib/mysql/
