version: '3.7'
services:
  elasticsearch:
    build: ./
    hostname: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
      - ./config:/etc/elasticsearch